<!DOCTYPE html>
<html>
<head>
    <title>Fund Realization Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #dc2626; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #1f2937; font-size: 24px; }
        .header p { margin: 5px 0 0; color: #6b7280; }
        
        .info-table { width: 100%; margin-bottom: 20px; }
        .info-table td { padding: 5px; vertical-align: top; }
        .label { font-weight: bold; width: 150px; color: #555; }

        .content-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .content-table th, .content-table td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        .content-table th { background-color: #f3f4f6; font-weight: bold; text-transform: uppercase; font-size: 10px; }
        .money { text-align: right; font-family: monospace; font-size: 13px; }

        .total-row td { background-color: #fef2f2; font-weight: bold; color: #dc2626; border-top: 2px solid #dc2626; }
        .balance-row td { background-color: #f9fafb; font-weight: bold; color: #1f2937; }

        .footer { margin-top: 50px; text-align: right; font-size: 10px; color: #999; }
        .signature { margin-top: 50px; width: 100%; }
        .signature td { text-align: center; width: 33%; }
        .sign-box { height: 80px; }
    </style>
</head>
<body>

    <div class="header">
        <h1>E-PRONOC</h1>
        <p>Fund Realization Report Document</p>
    </div>

    <table class="info-table">
        <tr>
            <td class="label">Registration Code</td>
            <td>: {{ $budget->proposal->registration_code ?? '-' }}</td>
        </tr>
        <tr>
            <td class="label">Proposal Title</td>
            <td>: <strong>{{ $budget->proposal->title }}</strong></td>
        </tr>
        <tr>
            <td class="label">Date Generated</td>
            <td>: {{ now()->format('d F Y') }}</td>
        </tr>
    </table>

    <table class="content-table">
        <thead>
            <tr>
                <th>Description</th>
                <th style="width: 150px; text-align: right;">Amount (IDR)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <strong>1. Direct Personnel Costs</strong><br>
                    <span style="color: #666; font-size: 10px;">Biaya Tenaga Lapangan (Non Dosen)</span>
                </td>
                <td class="money">{{ number_format($budget->direct_personnel_cost_fundrealization, 0, ',', '.') }}</td>
            </tr>
            <tr>
                <td>
                    <strong>2. Direct Non-Personnel Costs</strong><br>
                    <span style="color: #666; font-size: 10px;">Barang Habis Pakai (Non Aset)</span>
                </td>
                <td class="money">{{ number_format($budget->non_personnel_cost_fundrealization, 0, ',', '.') }}</td>
            </tr>
            <tr>
                <td>
                    <strong>3. Indirect Costs</strong><br>
                    <span style="color: #666; font-size: 10px;">Biaya Perjalanan Dinas & Pengelolaan</span>
                </td>
                <td class="money">{{ number_format($budget->indirect_cost_fundrealization, 0, ',', '.') }}</td>
            </tr>
            
            <tr class="total-row">
                <td style="text-align: right;">TOTAL REALIZATION</td>
                <td class="money">{{ number_format($budget->total_realization, 0, ',', '.') }}</td>
            </tr>
        </tbody>
    </table>

    <div style="margin-top: 20px; width: 50%; float: right;">
        <table class="content-table">
            <tr>
                <td>Initial Fund Plan</td>
                <td class="money">{{ number_format($budget->total_plan, 0, ',', '.') }}</td>
            </tr>
            <tr>
                <td>Total Used</td>
                <td class="money" style="color: #dc2626;">- {{ number_format($budget->total_realization, 0, ',', '.') }}</td>
            </tr>
            <tr class="balance-row">
                <td>REMAINING FUND</td>
                <td class="money">{{ number_format($budget->remaining_fund, 0, ',', '.') }}</td>
            </tr>
        </table>
    </div>
    
    <div style="clear: both;"></div>

    <div class="footer">
        Generated by System E-PRONOC | {{ now()->toDateTimeString() }}
    </div>

</body>
</html>